# -*- coding: utf-8 -*-
"""
Generates the interior pages, the footer/nav chrome, and sitemap.xml for
www.aplusdentalfl.com from tools/content.py.

    python3 tools/build.py

Output is plain static HTML committed to the repo — GitHub Pages still
serves the site with no build step. Regenerate after editing content.py.

Every .html file in the repo is generated, index.html included. Do not
hand-edit them — the next build overwrites your changes. Copy lives in
content.py, layout in this file, styling in assets/site.css.
"""
import html
import os
import re
import sys
from datetime import date

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from content import SITE, PRACTICE, DOCTORS, SERVICES, SERVICE_BY_SLUG  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
P = PRACTICE
GENERATED = "<!-- Generated by tools/build.py from tools/content.py. Edit content there, then re-run. -->"

ADDR_LINE = "%s, %s, %s %s" % (P["street"], P["city"], P["region"], P["zip"])
MAPS = ("https://www.google.com/maps/search/?api=1&amp;query="
        "6231+N+Federal+Hwy%2C+Fort+Lauderdale%2C+FL+33308")


# ---------------------------------------------------------------- helpers
def inline(text):
    """Minimal inline markup: **bold** and [label](href)."""
    text = html.escape(text, quote=False)
    text = re.sub(r"\[([^\]]+)\]\(([^)]+)\)", r'<a href="\2">\1</a>', text)
    text = re.sub(r"\*\*([^*]+)\*\*", r"<strong>\1</strong>", text)
    return text


def plain(text):
    """Strip inline markup — for JSON-LD, where markup would be noise."""
    text = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", text)
    return text.replace("**", "")


def esc(s):
    return html.escape(s, quote=True)


# ------------------------------------------------------------------ chrome
def head_html(*, title, desc, path, og_image, og_type="website", extra=""):
    url = SITE + path
    img = SITE + "/assets/" + og_image
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="color-scheme" content="light">
<title>{esc(title)}</title>
<meta name="description" content="{esc(desc)}">
<link rel="canonical" href="{url}">
<meta name="robots" content="index, follow, max-image-preview:large, max-snippet:-1">
<meta property="og:type" content="{og_type}">
<meta property="og:site_name" content="A+ Smile / BNY Dental P.C.">
<meta property="og:locale" content="en_US">
<meta property="og:title" content="{esc(title)}">
<meta property="og:description" content="{esc(desc)}">
<meta property="og:url" content="{url}">
<meta property="og:image" content="{img}">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="{esc(title)}">
<meta name="twitter:description" content="{esc(desc)}">
<meta name="twitter:image" content="{img}">
<meta name="geo.region" content="US-FL">
<meta name="geo.placename" content="Fort Lauderdale, Florida">
<link rel="icon" href="/assets/favicon.svg" type="image/svg+xml">
<link rel="apple-touch-icon" href="/assets/favicon.svg">
<link rel="preload" as="style" href="/assets/site.css">
<link rel="stylesheet" href="/assets/site.css">
{extra}</head>
<body>
{GENERATED}
"""


def nav_html():
    return f"""
<nav class="nav" aria-label="Primary">
  <div class="nav-inner">
    <a class="nav-logo" href="/">A<span class="logo-plus">+</span> Smile</a>
    <div class="nav-links">
      <a href="/services/">Services</a>
      <a href="/doctors/">Meet the Doctors</a>
      <a href="/#visit">Visit</a>
      <a class="nav-cta" href="tel:{P['phone_e164']}">Call {P['phone_display'].replace('-', '‑')}</a>
    </div>
  </div>
</nav>
"""


def footer_html():
    svc = "\n".join(
        '        <li><a href="/services/%s/">%s</a></li>' % (s["slug"], esc(s["nav"]))
        for s in SERVICES)
    docs = "\n".join(
        '        <li><a href="/doctors/%s/">%s</a></li>' % (d["slug"], esc(d["name"]))
        for d in DOCTORS)
    return f"""
<footer class="footer">
  <div class="footer-nav">
    <div class="footer-col">
      <h2>Services</h2>
      <ul>
{svc}
      </ul>
    </div>
    <div class="footer-col">
      <h2>Practice</h2>
      <ul>
{docs}
        <li><a href="/services/">All services</a></li>
        <li><a href="/#visit">Visit the office</a></li>
      </ul>
    </div>
    <div class="footer-col">
      <h2>Fort Lauderdale office</h2>
      <address>
        A+ Smile / BNY Dental P.C.<br>
        {P['street']}<br>
        {P['city']}, {P['region']} {P['zip']}<br>
        <a href="tel:{P['phone_e164']}">{P['phone_display']}</a><br>
        Urgent &middot; <a href="tel:{P['urgent_e164']}">{P['urgent_display']}</a><br>
        <a href="mailto:{P['email']}">{P['email']}</a>
      </address>
      <p><a href="{MAPS}" target="_blank" rel="noopener">Get directions</a></p>
    </div>
  </div>
  <p class="footer-motto">A<span class="logo-plus">+</span> Smile &mdash; The A+ standard of dentistry.</p>
  <p>&copy; {date.today().year} A+ Smile / BNY Dental P.C. &middot; {ADDR_LINE} &middot; <a href="tel:{P['phone_e164']}">{P['phone_display']}</a></p>
  <p class="fine">Information on this site is general and is not a substitute for an examination or personalized dental advice.</p>
</footer>

</body>
</html>
"""


def breadcrumbs_html(trail):
    """trail: [(label, href_or_None)] — last item is the current page."""
    items = []
    for label, href in trail:
        if href:
            items.append('      <li><a href="%s">%s</a></li>' % (href, esc(label)))
        else:
            items.append('      <li><span aria-current="page">%s</span></li>' % esc(label))
    return ('\n<nav class="breadcrumbs" aria-label="Breadcrumb">\n  <ol>\n'
            + "\n".join(items) + "\n  </ol>\n</nav>\n")


def cta_band_html(heading, body):
    return f"""
<section class="section cta-band">
  <h2>{heading}</h2>
  <p>{body}</p>
  <p class="nap">
    <strong>A+ Smile / BNY Dental P.C.</strong><br>
    {P['street']}, {P['city']}, {P['region']} {P['zip']}<br>
    <a href="tel:{P['phone_e164']}">{P['phone_display']}</a> &middot; <a href="mailto:{P['email']}">{P['email']}</a>
  </p>
  <a class="btn" href="tel:{P['phone_e164']}">Call {P['phone_display']}</a>
</section>
"""


def related_html(slugs, heading="Related care at A+ Smile"):
    cards = "\n".join(
        '    <a class="link-card" href="/services/%s/"><strong>%s</strong><span>%s</span></a>'
        % (s, esc(SERVICE_BY_SLUG[s]["nav"]), esc(SERVICE_BY_SLUG[s]["card"]))
        for s in slugs)
    return f"""
<section class="section related">
  <h2>{heading}</h2>
  <div class="link-grid">
{cards}
  </div>
</section>
"""


# ------------------------------------------------------------------ schema
def practice_node(full=False):
    node = {
        "@type": ["Dentist", "LocalBusiness"],
        "@id": SITE + "/#practice",
        "name": "A+ Smile",
        "alternateName": ["BNY Dental P.C.", "A+ Smile / BNY Dental P.C.", "A Plus Smile"],
        "legalName": "BNY Dental P.C.",
        "url": SITE + "/",
        "telephone": P["phone_e164"],
        "email": P["email"],
        "image": SITE + "/assets/before-after.jpg",
        "address": {
            "@type": "PostalAddress",
            "streetAddress": P["street"],
            "addressLocality": P["city"],
            "addressRegion": P["region"],
            "postalCode": P["zip"],
            "addressCountry": "US",
        },
        "hasMap": ("https://www.google.com/maps/search/?api=1&query="
                   "6231+N+Federal+Hwy%2C+Fort+Lauderdale%2C+FL+33308"),
    }
    if not full:
        return node
    node["description"] = (
        "A+ Smile / BNY Dental P.C. is a general, cosmetic, restorative and implant "
        "dental practice on North Federal Highway in Fort Lauderdale, Florida, led by "
        "Dr. Natalia Bartkova, DDS and Dr. Yuriy Kaziyev, DDS.")
    node["medicalSpecialty"] = "Dentistry"
    node["areaServed"] = [
        {"@type": "City", "name": c, "addressRegion": "FL"} for c in P["area_served"]]
    node["employee"] = [{"@id": SITE + "/doctors/%s/#person" % d["slug"]} for d in DOCTORS]
    node["knowsAbout"] = [s["service_type"] for s in SERVICES]
    node["hasOfferCatalog"] = {
        "@type": "OfferCatalog",
        "name": "Dental services in Fort Lauderdale",
        "itemListElement": [{
            "@type": "Offer",
            "itemOffered": {
                "@type": "Service",
                "@id": SITE + "/services/%s/#service" % s["slug"],
                "name": s["service_type"],
                "url": SITE + "/services/%s/" % s["slug"],
            },
        } for s in SERVICES],
    }
    return node


def breadcrumb_node(page_url, trail):
    return {
        "@type": "BreadcrumbList",
        "@id": page_url + "#breadcrumb",
        "itemListElement": [{
            "@type": "ListItem",
            "position": i + 1,
            "name": label,
            "item": SITE + (href if href else page_url.replace(SITE, "")),
        } for i, (label, href) in enumerate(trail)],
    }


def webpage_node(page_url, title, desc, trail, primary_image=None):
    node = {
        "@type": "WebPage",
        "@id": page_url + "#webpage",
        "url": page_url,
        "name": title,
        "description": desc,
        "isPartOf": {"@id": SITE + "/#website"},
        "about": {"@id": SITE + "/#practice"},
        "inLanguage": "en-US",
    }
    if trail:
        node["breadcrumb"] = {"@id": page_url + "#breadcrumb"}
    if primary_image:
        node["primaryImageOfPage"] = SITE + "/assets/" + primary_image
    return node


def faq_node(page_url, faqs):
    return {
        "@type": "FAQPage",
        "@id": page_url + "#faq",
        "mainEntity": [{
            "@type": "Question",
            "name": plain(q),
            "acceptedAnswer": {"@type": "Answer", "text": plain(a)},
        } for q, a in faqs],
    }


def jsonld(nodes):
    import json
    graph = {"@context": "https://schema.org", "@graph": nodes}
    return ('<script type="application/ld+json">\n'
            + json.dumps(graph, indent=2, ensure_ascii=False) + "\n</script>\n")


# ------------------------------------------------------------- page bodies
def render_body_blocks(blocks):
    out = []
    for heading, *rest in blocks:
        out.append("  <h2>%s</h2>" % esc(heading))
        for chunk in rest[0] if rest else []:
            if chunk is None:
                continue
            if isinstance(chunk, list):
                out.append("  <ul>")
                out += ["    <li>%s</li>" % inline(i) for i in chunk]
                out.append("  </ul>")
            else:
                out.append("  <p>%s</p>" % inline(chunk))
    return "\n".join(out)


def render_steps(steps):
    lis = "\n".join(
        "    <li><strong>%s</strong>%s</li>" % (esc(t), inline(b)) for t, b in steps)
    return '  <ol class="steps">\n%s\n  </ol>' % lis


def render_faqs(faqs):
    items = "\n".join(
        "    <details>\n      <summary>%s</summary>\n      <p>%s</p>\n    </details>"
        % (inline(q), inline(a)) for q, a in faqs)
    return ('\n<section class="section" id="faq">\n  <h2>Questions patients ask</h2>\n'
            '  <div class="faq">\n%s\n  </div>\n</section>\n' % items)


def write(path, text):
    full = os.path.join(ROOT, path)
    os.makedirs(os.path.dirname(full), exist_ok=True)
    with open(full, "w", encoding="utf-8") as fh:
        fh.write(text)
    print("  wrote %-52s %6d bytes" % (path, len(text.encode("utf-8"))))


# ------------------------------------------------------------- page types
def build_service(s):
    path = "/services/%s/" % s["slug"]
    url = SITE + path
    trail = [("Home", "/"), ("Services", "/services/"), (s["nav"], None)]

    parts = [render_body_blocks(s["body"])]
    if s.get("steps"):
        parts.append(render_steps(s["steps"]))
    if s.get("emergency_list"):
        parts.append("  <ul>\n" + "\n".join(
            "    <li><strong>%s</strong> — %s</li>" % (esc(t), inline(b))
            for t, b in s["emergency_list"]) + "\n  </ul>")
    if s.get("body_after"):
        parts.append(render_body_blocks(s["body_after"]))

    nodes = [
        practice_node(),
        webpage_node(url, s["title"], s["desc"], trail),
        breadcrumb_node(url, trail),
        {
            "@type": "Service",
            "@id": url + "#service",
            "name": "%s in Fort Lauderdale, FL" % s["service_type"],
            "serviceType": s["service_type"],
            "description": plain(s["lede"]),
            "url": url,
            "provider": {"@id": SITE + "/#practice"},
            "areaServed": [{"@type": "City", "name": c, "addressRegion": "FL"}
                           for c in P["area_served"]],
            "audience": {"@type": "Audience", "audienceType": "Dental patients"},
        },
        faq_node(url, s["faqs"]),
    ]

    doc = head_html(title=s["title"], desc=s["desc"], path=path,
                    og_image="before-after.jpg", og_type="article",
                    extra=jsonld(nodes))
    doc += nav_html()
    doc += breadcrumbs_html(trail)
    doc += f"""
<header class="page-hero">
  <h1>{esc(s['h1'])}</h1>
  <p class="lede">{inline(s['lede'])}</p>
  <div class="hero-actions">
    <a class="btn" href="tel:{P['phone_e164']}">Call {P['phone_display']}</a>
    <a class="btn-link" href="#faq">Common questions</a>
  </div>
</header>

<section class="section">
  <div class="prose">
{chr(10).join(parts)}
  </div>
</section>
"""
    doc += render_faqs(s["faqs"])
    doc += related_html(s["related"])
    doc += cta_band_html(
        "See us in Fort Lauderdale",
        "A+ Smile is accepting new patients on North Federal Highway. Call the office, "
        "or email and we&rsquo;ll reach out within one business day.")
    doc += footer_html()
    write("services/%s/index.html" % s["slug"], doc)


def build_services_index():
    path = "/services/"
    url = SITE + path
    trail = [("Home", "/"), ("Services", None)]
    title = "Dental Services in Fort Lauderdale, FL | A+ Smile"
    desc = ("General, cosmetic, restorative, implant and emergency dental services in "
            "Fort Lauderdale, FL. See what A+ Smile treats, or call (754) 802-1588.")

    groups = [
        ("Everyday and preventive care",
         "The visits that keep small problems small, for every age in the household.",
         ["family-dentistry", "preventive-dentistry", "periodontal-care"]),
        ("Repairing and replacing teeth",
         "Restoring function first — so anything cosmetic that follows is built on something solid.",
         ["restorative-dentistry", "dental-implants", "dentures"]),
        ("Changing how your smile looks",
         "Cosmetic treatment planned around your face, your bite and how you actually smile.",
         ["cosmetic-dentistry", "teeth-whitening", "invisalign"]),
        ("When something goes wrong",
         "Pain, swelling, a broken tooth or a lost crown — call before you wait it out.",
         ["emergency-dentistry"]),
    ]
    sections = []
    for h, sub, slugs in groups:
        cards = "\n".join(
            '    <a class="link-card" href="/services/%s/"><strong>%s</strong><span>%s</span></a>'
            % (sl, esc(SERVICE_BY_SLUG[sl]["nav"]), esc(SERVICE_BY_SLUG[sl]["card"]))
            for sl in slugs)
        sections.append(
            '<div class="service-group">\n  <h2>%s</h2>\n  <p>%s</p>\n'
            '  <div class="link-grid">\n%s\n  </div>\n</div>' % (esc(h), esc(sub), cards))

    nodes = [
        practice_node(),
        webpage_node(url, title, desc, trail),
        breadcrumb_node(url, trail),
        {
            "@type": "ItemList",
            "@id": url + "#services",
            "name": "Dental services offered in Fort Lauderdale",
            "itemListElement": [{
                "@type": "ListItem",
                "position": i + 1,
                "name": s["service_type"],
                "url": SITE + "/services/%s/" % s["slug"],
            } for i, s in enumerate(SERVICES)],
        },
    ]

    doc = head_html(title=title, desc=desc, path=path,
                    og_image="before-after.jpg", extra=jsonld(nodes))
    doc += nav_html()
    doc += breadcrumbs_html(trail)
    doc += f"""
<header class="page-hero">
  <h1>Dental Services in Fort Lauderdale</h1>
  <p class="lede">Routine care, cosmetic work, implants and emergencies &mdash; planned and
  completed in one office on North Federal Highway, by the same two doctors from consult
  to result.</p>
  <div class="hero-actions">
    <a class="btn" href="tel:{P['phone_e164']}">Call {P['phone_display']}</a>
    <a class="btn-link" href="/doctors/">Meet the doctors</a>
  </div>
</header>

<section class="section">
{chr(10).join(sections)}
</section>
"""
    doc += cta_band_html(
        "Not sure where to start?",
        "Call and describe what&rsquo;s going on. You&rsquo;ll get a straight answer about "
        "what kind of visit you actually need &mdash; and how soon.")
    doc += footer_html()
    write("services/index.html", doc)


def build_doctor(d):
    path = "/doctors/%s/" % d["slug"]
    url = SITE + path
    trail = [("Home", "/"), ("Meet the Doctors", "/doctors/"), (d["short"], None)]

    focus = "\n".join("    <li>%s</li>" % esc(f) for f in d["focus"])
    nodes = [
        practice_node(),
        webpage_node(url, d["title"], d["desc"], trail, primary_image=d["photo"]),
        breadcrumb_node(url, trail),
        {
            "@type": "Person",
            "@id": url + "#person",
            "name": d["name"],
            "givenName": d["plain"].split()[0],
            "familyName": d["plain"].split()[-1],
            "honorificPrefix": d["honorific"],
            "honorificSuffix": d["suffix"],
            "jobTitle": "Dentist",
            "description": plain(d["lede"]),
            "url": url,
            "image": SITE + "/assets/" + d["photo"],
            "worksFor": {"@id": SITE + "/#practice"},
            "alumniOf": {"@type": "CollegeOrUniversity", "name": d["alumni"]},
            "knowsAbout": d["focus"],
            "workLocation": {
                "@type": "Place",
                "name": "A+ Smile / BNY Dental P.C.",
                "address": {
                    "@type": "PostalAddress",
                    "streetAddress": P["street"],
                    "addressLocality": P["city"],
                    "addressRegion": P["region"],
                    "postalCode": P["zip"],
                    "addressCountry": "US",
                },
            },
        },
        faq_node(url, d["faqs"]),
    ]

    doc = head_html(title=d["title"], desc=d["desc"], path=path,
                    og_image=d["photo"], og_type="profile", extra=jsonld(nodes))
    doc += nav_html()
    doc += breadcrumbs_html(trail)
    doc += f"""
<header class="doctor-header">
  <img src="/assets/{d['photo']}" width="400" height="520"
       alt="{esc(d['name'])}, dentist at A+ Smile in Fort Lauderdale, Florida"
       fetchpriority="high" decoding="async">
  <div>
    <h1>{esc(d['name'])}</h1>
    <p class="doctor-meta">{esc(d['meta'])}</p>
    <p class="lede">{inline(d['lede'])}</p>
    <div class="hero-actions">
      <a class="btn" href="tel:{P['phone_e164']}">Call {P['phone_display']}</a>
      <a class="btn-link" href="/services/">See our services</a>
    </div>
  </div>
</header>

<section class="section">
  <div class="prose">
{render_body_blocks(d['body'])}
    <h2>Areas of focus</h2>
    <ul>
{focus}
    </ul>
  </div>
</section>
"""
    doc += render_faqs(d["faqs"])
    other = [x for x in DOCTORS if x["slug"] != d["slug"]]
    cards = "\n".join(
        '    <a class="link-card" href="/doctors/%s/"><strong>%s</strong><span>%s</span></a>'
        % (o["slug"], esc(o["name"]), esc(o["meta"])) for o in other)
    cards += ('\n    <a class="link-card" href="/services/"><strong>All dental services</strong>'
              '<span>Everything treated at the Fort Lauderdale office, in one place.</span></a>')
    doc += ('\n<section class="section related">\n  <h2>Also at A+ Smile</h2>\n'
            '  <div class="link-grid">\n%s\n  </div>\n</section>\n' % cards)
    doc += cta_band_html(
        "Book with %s" % d["short"],
        "A+ Smile is accepting new patients in Fort Lauderdale. Call the office, or email "
        "and we&rsquo;ll reach out within one business day.")
    doc += footer_html()
    write("doctors/%s/index.html" % d["slug"], doc)


def build_doctors_index():
    path = "/doctors/"
    url = SITE + path
    trail = [("Home", "/"), ("Meet the Doctors", None)]
    title = "Meet Our Fort Lauderdale Dentists | A+ Smile"
    desc = ("Dr. Natalia Bartkova, DDS and Dr. Yuriy Kaziyev, DDS treat every patient "
            "personally at A+ Smile in Fort Lauderdale, FL. Call (754) 802-1588.")

    cards = "\n".join(f"""    <div class="doctor">
      <img class="doctor-portrait" src="/assets/{d['photo']}" width="400" height="520"
           alt="{esc(d['name'])}, dentist at A+ Smile in Fort Lauderdale, Florida"
           {'fetchpriority="high"' if i == 0 else 'loading="lazy"'} decoding="async">
      <h2><a href="/doctors/{d['slug']}/">{esc(d['name'])}</a></h2>
      <p class="doctor-meta">{esc(d['meta'])}</p>
      <p>{inline(d['lede'])}</p>
      <p><a class="btn-link" href="/doctors/{d['slug']}/">Read {esc(d['short'])}&rsquo;s profile</a></p>
    </div>""" for i, d in enumerate(DOCTORS))

    nodes = [
        practice_node(),
        webpage_node(url, title, desc, trail),
        breadcrumb_node(url, trail),
        {
            "@type": "ItemList",
            "@id": url + "#doctors",
            "name": "Dentists at A+ Smile, Fort Lauderdale",
            "itemListElement": [{
                "@type": "ListItem", "position": i + 1, "name": d["name"],
                "url": SITE + "/doctors/%s/" % d["slug"],
            } for i, d in enumerate(DOCTORS)],
        },
    ]

    doc = head_html(title=title, desc=desc, path=path,
                    og_image="dr-bartkova.jpg", extra=jsonld(nodes))
    doc += nav_html()
    doc += breadcrumbs_html(trail)
    doc += f"""
<header class="page-hero">
  <h1>Meet Our Fort Lauderdale Dentists</h1>
  <p class="lede">Two doctors, one standard. You see the same faces at every visit, so your
  care stays personal from the first consult through to the result.</p>
</header>

<section class="section">
  <div class="doctors" style="margin-top:0">
{cards}
  </div>
</section>
"""
    doc += cta_band_html(
        "Become a patient",
        "A+ Smile is accepting new patients on North Federal Highway in Fort Lauderdale.")
    doc += footer_html()
    write("doctors/index.html", doc)


def last_modified(relpath):
    """The date this page's content actually last changed.

    Stamping every URL with today's date on every build makes <lastmod> a lie,
    and Google discounts sitemaps whose lastmod it cannot trust. So: if the
    file differs from HEAD right now (or is new), it changed today; otherwise
    use the date of the last commit that touched it. Falls back to today
    outside a git checkout.
    """
    import subprocess
    try:
        dirty = subprocess.run(["git", "status", "--porcelain", "--", relpath],
                               cwd=ROOT, capture_output=True, text=True, timeout=10)
        if dirty.returncode != 0:
            return date.today().isoformat()
        if dirty.stdout.strip():
            return date.today().isoformat()
        log = subprocess.run(["git", "log", "-1", "--format=%cs", "--", relpath],
                             cwd=ROOT, capture_output=True, text=True, timeout=10)
        stamp = log.stdout.strip()
        return stamp if stamp else date.today().isoformat()
    except (OSError, subprocess.SubprocessError):
        return date.today().isoformat()


def build_sitemap():
    urls = [("/", "1.0"), ("/services/", "0.9"), ("/doctors/", "0.8")]
    urls += [("/services/%s/" % s["slug"], "0.8") for s in SERVICES]
    urls += [("/doctors/%s/" % d["slug"], "0.7") for d in DOCTORS]
    body = "\n".join(
        "  <url>\n    <loc>%s%s</loc>\n    <lastmod>%s</lastmod>\n"
        "    <changefreq>monthly</changefreq>\n    <priority>%s</priority>\n  </url>"
        % (SITE, u, last_modified(u.lstrip("/") + "index.html"), pr) for u, pr in urls)
    write("sitemap.xml",
          '<?xml version="1.0" encoding="UTF-8"?>\n'
          '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
          + body + "\n</urlset>\n")


def build_404():
    title = "Page not found | A+ Smile, Fort Lauderdale Dentist"
    doc = head_html(title=title, desc="That page could not be found. Browse the dental services offered "
                    "at A+ Smile in Fort Lauderdale, FL, or call the office at (754) 802-1588.",
                    path="/404.html", og_image="before-after.jpg",
                    extra='<meta name="robots" content="noindex, follow">\n')
    doc = doc.replace('<meta name="robots" content="index, follow, '
                      'max-image-preview:large, max-snippet:-1">\n', "")
    doc += nav_html()
    doc += """
<header class="page-hero">
  <h1>That page moved.</h1>
  <p class="lede">The page you were looking for isn&rsquo;t here. Everything we treat is
  listed under services &mdash; or call the office and we&rsquo;ll point you to it.</p>
  <div class="hero-actions">
    <a class="btn" href="/services/">Browse services</a>
    <a class="btn-link" href="/">Back to the home page</a>
  </div>
</header>
"""
    doc += footer_html()
    write("404.html", doc)


def build_home():
    path = "/"
    url = SITE + path
    title = "Dentist in Fort Lauderdale, FL | A+ Smile / BNY Dental"
    desc = ("General, cosmetic, restorative and implant dentistry in Fort Lauderdale, FL, "
            "with Dr. Natalia Bartkova, DDS and Dr. Yuriy Kaziyev, DDS. Call (754) 802-1588.")

    nodes = [
        {
            "@type": "WebSite",
            "@id": SITE + "/#website",
            "url": SITE + "/",
            "name": "A+ Smile / BNY Dental P.C.",
            "description": desc,
            "publisher": {"@id": SITE + "/#practice"},
            "inLanguage": "en-US",
        },
        practice_node(full=True),
        webpage_node(url, title, desc, None, primary_image="before-after.jpg"),
    ]

    tiles = [
        ("Family &amp; general dentistry", "Exams, fillings and everyday care that keeps small problems small.", "/services/family-dentistry/", False),
        ("Preventive care", "Cleanings, digital X&#8209;rays and screenings on a schedule that fits your life.", "/services/preventive-dentistry/", False),
        ("Restorative dentistry", "Repair damaged or worn teeth so they look, feel and work right again.", "/services/restorative-dentistry/", False),
        ("Cosmetic dentistry", "Whitening, bonding and veneers designed around your face &mdash; not a template.", "/services/cosmetic-dentistry/", True),
        ("Dental implants", "Permanent replacement for single teeth or full arches, planned digitally.", "/services/dental-implants/", True),
        ("Crowns &amp; bridges", "Strong, natural-looking restorations matched precisely to your smile.", "/services/restorative-dentistry/", False),
        ("Invisalign &amp; clear aligners", "Straighter teeth with removable aligners, for adults and teens.", "/services/invisalign/", False),
        ("Teeth whitening", "Professional in-office and custom take-home whitening, supervised.", "/services/teeth-whitening/", False),
        ("Dentures", "Full, partial and implant-supported options, fitted for comfort.", "/services/dentures/", False),
        ("Periodontal care", "Treatment for bleeding, receding and inflamed gums.", "/services/periodontal-care/", False),
        ("Emergency dentistry", "Toothache, broken tooth or swelling &mdash; call before you wait it out.", "/services/emergency-dentistry/", False),
        ("Second opinions", "Honest treatment planning when another office has quoted major work.", "/doctors/dr-yuriy-kaziyev/", False),
    ]
    cards = "\n".join(
        '    <a class="card%s" href="%s">\n      <h3>%s</h3>\n      <p>%s</p>\n'
        '      <p class="card-more">Learn more &rarr;</p>\n    </a>'
        % (" card-popular" if pop else "", href, name, blurb)
        for name, blurb, href, pop in tiles)

    doc = head_html(title=title, desc=desc, path=path,
                    og_image="before-after.jpg", extra=jsonld(nodes))
    doc += nav_html()
    doc += f"""
<header class="hero" id="top">
  <div class="hero-copy">
    <span class="hero-badge">Now welcoming new patients in Fort Lauderdale</span>
    <h1>Smile, naturally.<span class="h1-sub">Modern dentistry in Fort Lauderdale.</span></h1>
    <p class="hero-motto">The A+ standard of dentistry.</p>
    <p class="hero-sub">General, cosmetic, restorative and implant care from two doctors who
    take their time with every patient &mdash; all in one office on North Federal Highway.</p>
    <div class="hero-actions">
      <a class="btn" href="#visit">Book a consult</a>
      <a class="btn-link" href="/services/">See our services</a>
    </div>
    <ul class="trust-row">
      <li>Same-week appointments</li>
      <li>Most insurance accepted</li>
      <li>Free implant &amp; cosmetic consults</li>
    </ul>
  </div>
  <figure class="hero-figure">
    <img src="/assets/before-after.jpg" width="760" height="754"
         alt="Before and after treatment at A+ Smile in Fort Lauderdale: upper front teeth restored with crowns and veneers"
         fetchpriority="high" decoding="async">
    <figcaption><strong>Real patient, real result.</strong> Smile restoration with crowns and
    veneers &mdash; planned and completed in this office.</figcaption>
  </figure>
</header>

<section class="section alt-tint" id="doctors">
  <div class="section-inner">
  <h2>Meet your Fort Lauderdale dentists.</h2>
  <p class="section-sub">Two doctors, one standard &mdash; you&rsquo;ll see the same faces at every
  visit, so your care stays personal from consult to completion.</p>
  <div class="doctors">
    <div class="doctor">
      <img class="doctor-portrait" src="/assets/dr-bartkova.jpg" width="400" height="520"
           alt="Dr. Natalia Bartkova, DDS, general and cosmetic dentist at A+ Smile in Fort Lauderdale"
           loading="lazy" decoding="async">
      <h3><a href="/doctors/dr-natalia-bartkova/">Dr. Natalia Bartkova, DDS</a></h3>
      <p class="doctor-meta">General, restorative &amp; cosmetic dentistry &middot; NYU College of Dentistry</p>
      <p>For Dr. Bartkova, the appointment isn&rsquo;t finished until you understand it. She&rsquo;s known
      for slowing down, walking patients through every option in plain language, and never rushing a
      decision. Her philosophy: a healthy smile starts with strong teeth and healthy gums, not just a
      white one. Anxious patients tend to leave her chair wondering what they were nervous about.</p>
      <a class="btn-link doctor-link" href="/doctors/dr-natalia-bartkova/">Read Dr. Bartkova&rsquo;s profile</a>
    </div>
    <div class="doctor">
      <img class="doctor-portrait" src="/assets/dr-kaziyev.jpg" width="400" height="520"
           alt="Dr. Yuriy Kaziyev, DDS, implant and restorative dentist at A+ Smile in Fort Lauderdale"
           loading="lazy" decoding="async">
      <h3><a href="/doctors/dr-yuriy-kaziyev/">Dr. Yuriy Kaziyev, DDS</a></h3>
      <p class="doctor-meta">Implant, restorative &amp; cosmetic dentistry &middot; NYU College of Dentistry</p>
      <p>Dr. Kaziyev cared for families in Brooklyn for years before bringing his practice to Fort
      Lauderdale. He specializes in the work that changes how a smile looks and functions &mdash;
      <a href="/services/dental-implants/">implants</a>, same-day crowns, full-arch restorations and
      <a href="/services/invisalign/">clear aligners</a> &mdash; all planned digitally so results are
      precise and comfortable.</p>
      <div class="doctor-quote">
        <div class="review-stars" aria-hidden="true">&#9733;&#9733;&#9733;&#9733;&#9733;</div>
        <blockquote>&ldquo;Dr. Kaziyev has a very gentle touch. The work he did was painless and quick.
        Highly recommend the office to all friends and family.&rdquo;</blockquote>
        <p class="review-source">Verified patient review &middot; WebMD</p>
      </div>
      <a class="btn-link doctor-link" href="/doctors/dr-yuriy-kaziyev/">Read Dr. Kaziyev&rsquo;s profile</a>
    </div>
  </div>
  </div>
</section>

<section class="section" id="offers">
  <h2>Start with a smart first visit.</h2>
  <p class="section-sub">Three easy ways to get in the chair &mdash; pick the one that fits where
  your smile is today.</p>
  <div class="offers">
    <a class="offer" href="#visit">
      <span class="offer-tag">New patients</span>
      <h3>New Patient Exam</h3>
      <p class="offer-sub">Comprehensive exam, digital X&#8209;rays, and a clear plan for your smile
      &mdash; all in one visit.</p>
      <span class="offer-cta">Book my exam</span>
    </a>
    <a class="offer offer-featured" href="/services/dental-implants/">
      <span class="offer-tag">Most requested</span>
      <h3>Free Implant Consult</h3>
      <p class="offer-sub">Missing or failing teeth? Sit down with the doctor, see your options, and
      get honest pricing &mdash; no obligation.</p>
      <span class="offer-cta">Claim my consult</span>
    </a>
    <a class="offer" href="/services/cosmetic-dentistry/">
      <span class="offer-tag">Cosmetics</span>
      <h3>Free Smile Consult</h3>
      <p class="offer-sub">Whitening, veneers, or a full makeover &mdash; find out what&rsquo;s possible
      for your smile and your budget.</p>
      <span class="offer-cta">See what&rsquo;s possible</span>
    </a>
  </div>
</section>

<section class="section alt-tint" id="services">
  <div class="section-inner">
  <h2>Everything your smile needs.<br>In one place.</h2>
  <p class="section-sub">From routine cleanings to full smile makeovers, care is planned and
  completed under one roof in Fort Lauderdale &mdash; no bouncing between offices.</p>
  <div class="grid">
{cards}
  </div>
  <p style="margin-top:32px"><a class="btn-link" href="/services/">See all dental services &rarr;</a></p>
  </div>
</section>

<section class="section experience">
  <h2>The A<span class="logo-plus">+</span> Experience</h2>
  <ul class="exp-list">
    <li>Concierge&#8209;level service for a <strong>stress&#8209;free, judgment&#8209;free visit</strong>
    &mdash; from your first call to your final result.</li>
    <li><strong>The same two doctors</strong> at every visit &mdash; your care stays personal, never
    handed off.</li>
    <li><strong>Modern treatment</strong> planned with current digital technology.</li>
    <li>Results that are <strong>as beautiful as they are healthy</strong>.</li>
    <li><strong>Clear, upfront pricing</strong> &mdash; no surprises, ever.</li>
  </ul>
  <div class="exp-cta">
    <a class="btn" href="#visit">Book now</a>
  </div>
</section>

<section class="section" id="visit">
  <h2>Visit us in Fort Lauderdale.</h2>
  <p class="section-sub">Now accepting new patients. Call, or email us and we&rsquo;ll reach out
  within one business day.</p>
  <div class="visit">
    <div class="visit-col">
      <h3>Location</h3>
      <p>A+ Smile / BNY Dental P.C.<br>{P['street']}<br>{P['city']}, {P['region']} {P['zip']}</p>
      <p><a href="{MAPS}" target="_blank" rel="noopener">Get directions</a></p>
      <p>We&rsquo;re on North Federal Highway in north Fort Lauderdale, a short drive from Oakland
      Park, Wilton Manors, Lauderdale&#8209;by&#8209;the&#8209;Sea, Lighthouse Point and Pompano Beach.</p>
    </div>
    <div class="visit-col">
      <h3>Contact</h3>
      <p>Office &middot; <a href="tel:{P['phone_e164']}">{P['phone_display']}</a></p>
      <p>Urgent &middot; <a href="tel:{P['urgent_e164']}">{P['urgent_display']}</a></p>
      <p><a href="mailto:{P['email']}">{P['email']}</a></p>
      <p>Dental emergency? See <a href="/services/emergency-dentistry/">what to do first</a>.</p>
    </div>
  </div>

  <div class="contact-actions">
    <a class="btn" href="tel:{P['phone_e164']}">Call now &mdash; accepting new patients</a>
    <a class="btn btn-outline" href="mailto:{P['email']}?subject=Consult%20request%20%E2%80%94%20A%2B%20Smile&amp;body=Name%3A%0APhone%3A%0AWhat%20can%20we%20help%20with%3F%0A">Email us to request a consult</a>
  </div>
</section>
"""
    doc += footer_html()
    write("index.html", doc)


if __name__ == "__main__":
    print("Building www.aplusdentalfl.com pages...")
    build_home()
    build_services_index()
    for s in SERVICES:
        build_service(s)
    build_doctors_index()
    for d in DOCTORS:
        build_doctor(d)
    build_404()
    build_sitemap()
    print("Done.")
